#!/usr/bin/env python3
"""Generate ParameterRegistryData.inl and schemas/voxp4-parameters-v1.json from voxlink_params.json.

Run:
    python scripts/generate_param_registry.py
"""
from __future__ import annotations

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(ROOT, "src", "voxlink", "generated", "voxlink_params.json")
OUT_INL_PATH = os.path.join(ROOT, "src", "model", "ParameterRegistryData.inl")
OUT_SCHEMA_PATH = os.path.join(ROOT, "schemas", "voxp4-parameters-v1.json")

# Canonical definitions verified against VoxP4 DSP source headers
CANONICAL_ENUMS: dict[str, list[str]] = {
    "harmony.mode": ["Fixed", "Diatonic", "Midi"],
    "harmony.key": ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"],
    "harmony.scale": [
        "Major",
        "NaturalMinor",
        "HarmonicMinor",
        "MelodicMinor",
        "Dorian",
        "Phrygian",
        "Lydian",
        "Mixolydian",
        "Locrian",
        "MajorPentatonic",
        "MinorPentatonic",
        "BluesMinor",
    ],
    "harmony.voice1.non_scale_policy": ["Nearest", "Chromatic", "Bypass"],
    "delay.left_subdivision": [
        "Whole",
        "Half",
        "Quarter",
        "Eighth",
        "Sixteenth",
        "ThirtySecond",
        "DottedHalf",
        "DottedQuarter",
        "DottedEighth",
        "DottedSixteenth",
        "TripletQuarter",
        "TripletEighth",
        "TripletSixteenth",
    ],
    "delay.right_subdivision": [
        "Whole",
        "Half",
        "Quarter",
        "Eighth",
        "Sixteenth",
        "ThirtySecond",
        "DottedHalf",
        "DottedQuarter",
        "DottedEighth",
        "DottedSixteenth",
        "TripletQuarter",
        "TripletEighth",
        "TripletSixteenth",
    ],
    "output.spatial_routing": ["Parallel", "DelayIntoReverb"],
    "output.spatial_source": ["Input", "PostDynamics", "PostHarmony"],
    "chorus.mode": ["Chorus", "Ensemble", "Dimension", "Microshift"],
    "chorus.subdivision": [
        "Whole",
        "Half",
        "Quarter",
        "Eighth",
        "Sixteenth",
        "ThirtySecond",
        "DottedHalf",
        "DottedQuarter",
        "DottedEighth",
        "DottedSixteenth",
        "TripletQuarter",
        "TripletEighth",
        "TripletSixteenth",
    ],
    "drive.mode": ["Warm", "Overdrive", "Megaphone"],
}


def to_pascal_case(key: str) -> str:
    parts = re.split(r"[._]", key)
    return "".join(p.capitalize() for p in parts)


def main():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    params = data["parameters"]
    params.sort(key=lambda p: p["id"])

    type_map = {
        "bool": "ParamType::Bool",
        "int": "ParamType::Int",
        "float": "ParamType::Float",
        "enum": "ParamType::Enum",
    }

    # 1. Generate C++ ParameterRegistryData.inl
    lines = [
        "// GENERATED by scripts/generate_param_registry.py. Do not edit by hand.",
        "#pragma once",
        "",
        "#include \"ParameterRegistry.h\"",
        "",
        "static const ParamDescriptor kParamDescriptors[VOXP4_PARAM_COUNT] = {",
    ]

    export_params = []

    for idx, p in enumerate(params):
        ptype = type_map[p["type"]]
        pid = p["id"]
        key = p["key"]
        semantic = to_pascal_case(key)
        dsp = p.get("dsp_binding", "")
        display = p.get("display", "")
        pmin = float(p["min"])
        pmax = float(p["max"])
        pdef = float(p["default"])
        group = p.get("group", "")
        unit = p.get("unit", "")
        step = float(p.get("step", 1.0))

        lines.append(
            f"    {{ {pid}u, {idx}u, \"{key}\", \"{semantic}\", \"{dsp}\", \"{display}\", "
            f"{ptype}, {pmin}f, {pmax}f, {pdef}f }},"
        )

        param_dict = {
            "name": semantic,
            "key": key,
            "display": display,
            "group": group,
            "type": p["type"],
            "min": pmin,
            "max": pmax,
            "default": pdef,
            "step": step,
            "unit": unit,
        }
        if p["type"] == "enum":
            if key in CANONICAL_ENUMS:
                param_dict["values"] = CANONICAL_ENUMS[key]
            else:
                raise ValueError(f"Missing canonical enum definition for: {key}")

        export_params.append(param_dict)

    lines.append("};")
    lines.append("")

    with open(OUT_INL_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"Generated {len(params)} parameter descriptors into {OUT_INL_PATH}")

    # 2. Generate Web parameter contract JSON
    contract = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "VoxP4ParameterContractV1",
        "description": "Canonical public parameter catalog for VoxP4 Portable Library V1",
        "contractVersion": 1,
        "parameterCount": len(export_params),
        "parameters": export_params,
    }

    os.makedirs(os.path.dirname(OUT_SCHEMA_PATH), exist_ok=True)
    with open(OUT_SCHEMA_PATH, "w", encoding="utf-8", newline="\n") as f:
        json.dump(contract, f, indent=2)
        f.write("\n")

    print(f"Generated Web parameter contract JSON into {OUT_SCHEMA_PATH}")


if __name__ == "__main__":
    main()
