#!/usr/bin/env python3
"""Generate ParameterRegistryData.inl from src/voxlink/generated/voxlink_params.json.

Run:
    python scripts/generate_param_registry.py
"""
from __future__ import annotations

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(ROOT, "src", "voxlink", "generated", "voxlink_params.json")
OUT_PATH = os.path.join(ROOT, "src", "model", "ParameterRegistryData.inl")


def to_pascal_case(key: str) -> str:
    # e.g. "harmony.enable" -> "HarmonyEnable"
    # "delay.feedback_lowpass_hz" -> "DelayFeedbackLowpassHz"
    # "chorus.microshift_left_cents" -> "ChorusMicroshiftLeftCents"
    parts = re.split(r"[._]", key)
    return "".join(p.capitalize() for p in parts)


def main():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    params = data["parameters"]
    params.sort(key=lambda p: p["id"])

    type_map = {
        "bool": "ParamType::Bool",
        "int": "ParamType::Int",
        "float": "ParamType::Float",
        "enum": "ParamType::Enum",
    }

    lines = [
        "// GENERATED by scripts/generate_param_registry.py. Do not edit by hand.",
        "#pragma once",
        "",
        "#include \"ParameterRegistry.h\"",
        "",
        "static const ParamDescriptor kParamDescriptors[VOXP4_PARAM_COUNT] = {",
    ]

    for idx, p in enumerate(params):
        ptype = type_map[p["type"]]
        pid = p["id"]
        key = p["key"]
        semantic = to_pascal_case(key)
        dsp = p.get("dsp_binding", "")
        display = p.get("display", "")
        pmin = float(p["min"])
        pmax = float(p["max"])
        pdef = float(p["default"])

        lines.append(
            f"    {{ {pid}u, {idx}u, \"{key}\", \"{semantic}\", \"{dsp}\", \"{display}\", "
            f"{ptype}, {pmin}f, {pmax}f, {pdef}f }},"
        )

    lines.append("};")
    lines.append("")

    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"Generated {len(params)} parameter descriptors into {OUT_PATH}")


if __name__ == "__main__":
    main()
